### ISSUE TITLE
Any plans on merging with tigris?

### ISSUE THREAD

**Issue by ogr3** [tesla/m2eclipse-subclipse#8]
The tigris developers have a project here https://github.com/markphip/m2eclipse-subclipse

It does not support m2e 1.2 that was released for Juno, but they have an update site. Could someone please make a pull request there to incorporate the changes here?

**Comment by markphip** [comment]
I was just notified of this issue.  I posted a new build that removes the m2e version constraint.  From what I can see, it works with 1.2.
